server:
  port : 8080

spring:
  datasource:
    url : jdbc:postgresql://localhost:5432/prepare2travel_db
    username : postgres
    password : admin

  jpa:
    generate-ddl : true
    hibernate :
      ddl-auto : create
    properties:
      hibernate:
        dialect : org.hibernate.dialect.PostgreSQLDialect

  output:
    ansi:
      enabled : always


command-line-runner:
  data-loading:
    travels:
      enabled : false
    presets:
      enabled: true

springdoc:
  show-actuator: false
  swagger-ui:
    enabled: true
    path: /swagger-ui.html